'use client';
import { useState, useEffect } from 'react';
import DashboardContent from './DashboardContent';

const L='#b57bee',LL='#f3e8ff',LB='#e9d5ff',TH='#1e0a35',TM='#9b87ba';
const card={background:'#fff',border:`1.5px solid ${LB}`,borderRadius:'16px',padding:'20px'};
const inp={width:'100%',padding:'10px 14px',border:`1.5px solid ${LB}`,borderRadius:'10px',background:'#fff',color:TH,fontSize:'14px'};
const lbl={display:'block',fontSize:'13px',fontWeight:'600',marginBottom:'8px',color:'#4a3b66'};

const availableAgents=[
  {id:'agent-1',name:'Research Agent',role:'Data Gathering'},
  {id:'agent-2',name:'Writer Agent',role:'Content Generation'},
  {id:'agent-3',name:'Reviewer Agent',role:'Quality Control'},
  {id:'agent-4',name:'Coder Agent',role:'Development'},
];

export default function TaskMainPanel({selectedTask,onTaskUpdate}){
  const [formData,setFormData]=useState({name:'',description:'',agents:[],workflowSteps:''});
  const [isGenerating,setIsGenerating]=useState(false);
  const [isSaving,setIsSaving]=useState(false);
  const [isRunning,setIsRunning]=useState(false);

  useEffect(()=>{if(selectedTask)setFormData({name:selectedTask.name||'',description:selectedTask.description||'',agents:selectedTask.agents||[],workflowSteps:selectedTask.workflowSteps||''});},[selectedTask]);

  const handleChange=(e)=>setFormData(p=>({...p,[e.target.name]:e.target.value}));
  const toggle=(id)=>setFormData(p=>({...p,agents:p.agents.includes(id)?p.agents.filter(a=>a!==id):[...p.agents,id]}));
  const handleGenerate=async()=>{if(!formData.description)return;setIsGenerating(true);await new Promise(r=>setTimeout(r,2000));setFormData(p=>({...p,workflowSteps:'Based on your description:\n\n1. Analyze input requirements.\n2. Coordinate with agents.\n3. Execute task constraints.\n4. Review output.\n\n(Generated by LLM)'}));setIsGenerating(false);};
  const handleSave=async()=>{setIsSaving(true);await new Promise(r=>setTimeout(r,500));onTaskUpdate({...selectedTask,...formData,status:'saved'});setIsSaving(false);};
  const handleDryRun=async()=>{setIsRunning(true);await new Promise(r=>setTimeout(r,1500));alert('Dry run completed!');setIsRunning(false);};

  if(!selectedTask)return<DashboardContent/>;

  return(
    <div className="flex-1 flex flex-col h-full overflow-y-auto" style={{background:'#fafafa'}}>
      <div className="p-6" style={{borderBottom:`1.5px solid ${LB}`,background:'#fff'}}>
        <h1 className="text-2xl font-bold" style={{color:TH}}>Edit Task Configuration</h1>
        <p className="text-sm mt-1" style={{color:TM}}>Define task parameters, assign agents, and generate workflow steps.</p>
      </div>
      <div className="p-6 max-w-4xl mx-auto w-full space-y-5">
        <div style={card}><label style={lbl}>Task Name</label><input type="text" name="name" value={formData.name} onChange={handleChange} style={inp}/></div>
        <div style={card}><label style={lbl}>Description</label><textarea name="description" rows="4" value={formData.description} onChange={handleChange} placeholder="Describe what this task should accomplish..." style={{...inp,resize:'vertical'}}/></div>
        <div style={card}>
          <label style={lbl}>Assign Agents</label>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {availableAgents.map(a=>(
              <label key={a.id} className="flex items-center p-3 rounded-xl cursor-pointer transition-all"
                style={formData.agents.includes(a.id)?{background:LL,border:`1.5px solid ${L}`}:{background:'#fafafa',border:`1.5px solid ${LB}`}}>
                <input type="checkbox" checked={formData.agents.includes(a.id)} onChange={()=>toggle(a.id)} className="w-4 h-4 mr-3" style={{accentColor:L}}/>
                <div><span className="block text-sm font-medium" style={{color:TH}}>{a.name}</span><span className="block text-xs" style={{color:TM}}>{a.role}</span></div>
              </label>
            ))}
          </div>
        </div>
        <div style={card}>
          <button type="button" onClick={handleGenerate} disabled={!formData.description||isGenerating}
            className="flex items-center gap-2 px-5 py-2.5 text-sm font-semibold text-white rounded-xl hover:opacity-85 disabled:opacity-50 mb-4"
            style={{background:L,boxShadow:`0 4px 12px rgba(181,123,238,0.3)`}}>
            {isGenerating?(<><svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>Generating...</>):'✨ Generate Workflow Steps (LLM)'}
          </button>
          <label style={lbl}>Workflow Steps</label>
          <textarea name="workflowSteps" rows="6" value={formData.workflowSteps} onChange={handleChange}
            placeholder="Workflow steps appear here after generation..."
            style={{...inp,resize:'vertical',fontFamily:'monospace',fontSize:'13px',background:'#fafafa'}}/>
        </div>
        <div className="flex flex-wrap gap-4 pb-6">
          <button type="button" onClick={handleSave} disabled={isSaving}
            className="flex-1 md:flex-none px-6 py-3 text-white font-semibold rounded-xl hover:opacity-85 disabled:opacity-50"
            style={{background:L,boxShadow:`0 4px 12px rgba(181,123,238,0.3)`}}>
            {isSaving?'Saving...':'Save Task'}
          </button>
          <button type="button" onClick={handleDryRun} disabled={isRunning||!formData.workflowSteps}
            className="flex-1 md:flex-none px-6 py-3 font-semibold rounded-xl hover:opacity-85 disabled:opacity-50"
            style={{background:LL,color:L,border:`1.5px solid ${LB}`}}>
            {isRunning?'Running...':'Dry Run'}
          </button>
        </div>
      </div>
    </div>
  );
}
